### PR TITLE
Add support for iPad

### PR DESCRIPTION
**Pull request by einarlove**
Is there a reason why iPad was not supported in the library? Videos are playing fine on my iPad.

### CODE REVIEW

**Comment by bfred-it** [comment]
iPad plays video inline autonomously, you don't need this library. Are you using it for `autoplay`?

**Comment by einarlove** [comment]
Yes, I'm using for playing videos without user interaction. I've made a video carousel which changes to next video when the last one ends.
I've made a fork that I use, but if you do not want to open it for iPads, there could be an option instead which overrides the userAgent test.

**Comment by einarlove** [comment]
If you know of a solution to using the native iPad player and make it possible to play/pause with javascript, please let me know.

**Comment by bfred-it** [comment]
You still need user interaction if you want audio. If not, use this:

```
makeVideoPlayableInline(video, /*hasAudio*/ false, /*onlyOnIphone*/ false);
```

**Comment by einarlove** [comment]
Was not aware of the `onlyWhenNeeded` option. It solves my problem, thanks!

**Comment by barm** [comment]
``` js
if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
    makeVideoPlayableInline(video, /*hasAudio*/ false, false /*this will will skip the integrated device test*/);
}
```
Won't think unnecessarily take over playback in cases where autoplay and inline are natively supported (i.e. iOS 10)? 

I ended up writing a check around the makeVideoPlayableInline:

```js
const supportsInlineVideo = matchMedia('(-webkit-video-playable-inline)').matches;
if (/iPhone|iPad|iPod/i.test(navigator.userAgent) && !supportsInlineVideo) {
  makeVideoPlayableInline(video, false, false);
}
```

Seems like some of the confusion comes from people (myself included) wanting to play inline, but also enable `autoplay` in browsers that don't natively support it, and the API is primarily focused on the playable inline use-case.

**Comment by bfred-it** [comment]
Good point! Thanks for the snippet :)

**Comment by bfred-it** [comment]
In the v2 beta I simplified the usage on iPad. Can you try it and let me know how it goes?

- [v2 changelog](https://github.com/bfred-it/iphone-inline-video/blob/2.0/CHANGELOG.md)
- [v2 usage documentation](https://github.com/bfred-it/iphone-inline-video/tree/2.0#install)
- [iphone-inline-video.js](https://github.com/bfred-it/iphone-inline-video/tree/2.0/dist)
- If you use npm, you can install the beta with: `npm install iphone-inline-video@next`

**Comment by bfred-it** [comment]
v2.0.0 has been published :)

Now you can use the `iPad` option:

```js
enableInlineVideo(video, {
    iPad: true
});
```

**Pull request closed without merging**
